# Generated by Django 5.1.2 on 2026-05-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='seasoning',
            new_name='seasonings',
        ),
    ]
