# Generated by Django 5.1.2 on 2026-05-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='seasonings',
        ),
    ]
